//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace latex_curriculum_vitae.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("latex_curriculum_vitae.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mrs ähnelt.
        /// </summary>
        public static string AddressFemale {
            get {
                return ResourceManager.GetString("AddressFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mr ähnelt.
        /// </summary>
        public static string AddressMale {
            get {
                return ResourceManager.GetString("AddressMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application_documents_ ähnelt.
        /// </summary>
        public static string AppDoc {
            get {
                return ResourceManager.GetString("AppDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Additional_Certificates_ ähnelt.
        /// </summary>
        public static string Cert {
            get {
                return ResourceManager.GetString("Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job_References_ ähnelt.
        /// </summary>
        public static string Cos {
            get {
                return ResourceManager.GetString("Cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email sent ähnelt.
        /// </summary>
        public static string CsvEmailSent {
            get {
                return ResourceManager.GetString("CsvEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p&gt;{0}&lt;br&gt;
        ///&lt;p&gt;I am sending you my application documents attached.&lt;br&gt;
        ///&lt;p&gt;Sincerly&lt;/p&gt;
        ///&lt;p align=left&gt;{1}&lt;br&gt;
        ///&lt;center&gt;&lt;img src=&quot;&quot;cid:{2}&quot;&quot; width=&quot;&quot;10%&quot;&quot;&gt;&lt;/center&gt;&lt;/p&gt; ähnelt.
        /// </summary>
        public static string EmailHTML {
            get {
                return ResourceManager.GetString("EmailHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You haven&apos;t set all needed fields for sending emails. I open for you the Usersettings Window. ähnelt.
        /// </summary>
        public static string EmailNotSet {
            get {
                return ResourceManager.GetString("EmailNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t send email. ähnelt.
        /// </summary>
        public static string EmailNotSetHeader {
            get {
                return ResourceManager.GetString("EmailNotSetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}
        ///
        ///I am sending you my application documents attached.
        ///
        ///Sincerely
        ///{1} ähnelt.
        /// </summary>
        public static string EmailPlain {
            get {
                return ResourceManager.GetString("EmailPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sent ähnelt.
        /// </summary>
        public static string EnumStatus0 {
            get {
                return ResourceManager.GetString("EnumStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirmed ähnelt.
        /// </summary>
        public static string EnumStatus1 {
            get {
                return ResourceManager.GetString("EnumStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invited ähnelt.
        /// </summary>
        public static string EnumStatus2 {
            get {
                return ResourceManager.GetString("EnumStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rejected ähnelt.
        /// </summary>
        public static string EnumStatus3 {
            get {
                return ResourceManager.GetString("EnumStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string GenderUnknown {
            get {
                return ResourceManager.GetString("GenderUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HR department ähnelt.
        /// </summary>
        public static string HRDepartment {
            get {
                return ResourceManager.GetString("HRDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Now i open for you the directory in the explorer, what contains your PDFs. ähnelt.
        /// </summary>
        public static string MsgDirFinalPdf {
            get {
                return ResourceManager.GetString("MsgDirFinalPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your email is now sent. You can do the next job application. ähnelt.
        /// </summary>
        public static string MsgEmailSent {
            get {
                return ResourceManager.GetString("MsgEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string MsgHeaderInfo {
            get {
                return ResourceManager.GetString("MsgHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You starting the app the first time. Please add your user settings in the window. ähnelt.
        /// </summary>
        public static string MsgSetupCheckConfig {
            get {
                return ResourceManager.GetString("MsgSetupCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Configuration ähnelt.
        /// </summary>
        public static string MsgSetupCheckConfigHeader {
            get {
                return ResourceManager.GetString("MsgSetupCheckConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please close the App and follow the documentation. I open it for you. ähnelt.
        /// </summary>
        public static string MsgSetupCheckDocument {
            get {
                return ResourceManager.GetString("MsgSetupCheckDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check documents path ähnelt.
        /// </summary>
        public static string MsgSetupCheckDocumentHeader {
            get {
                return ResourceManager.GetString("MsgSetupCheckDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You starting the app the first time. I prepare now the directory structure and copy the needed files to: ähnelt.
        /// </summary>
        public static string MsgSetupCheckDocumentsCopy {
            get {
                return ResourceManager.GetString("MsgSetupCheckDocumentsCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I haven&apos;t found TeXLive. Now i open a Browser, where you can download it. Please close this app and install TexLive. ähnelt.
        /// </summary>
        public static string MsgSetupCheckLatex {
            get {
                return ResourceManager.GetString("MsgSetupCheckLatex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check LaTEX ähnelt.
        /// </summary>
        public static string MsgSetupCheckLatexHeader {
            get {
                return ResourceManager.GetString("MsgSetupCheckLatexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Database ähnelt.
        /// </summary>
        public static string MWGoDatabase {
            get {
                return ResourceManager.GetString("MWGoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write your Job-Application ähnelt.
        /// </summary>
        public static string MWStartWriteJobApplication {
            get {
                return ResourceManager.GetString("MWStartWriteJobApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main Menue ähnelt.
        /// </summary>
        public static string MWTitle {
            get {
                return ResourceManager.GetString("MWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View or Change User Settings ähnelt.
        /// </summary>
        public static string MWUsersettings {
            get {
                return ResourceManager.GetString("MWUsersettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dear Mrs ähnelt.
        /// </summary>
        public static string SalutationFemale {
            get {
                return ResourceManager.GetString("SalutationFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dear Mr ähnelt.
        /// </summary>
        public static string SalutationMale {
            get {
                return ResourceManager.GetString("SalutationMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dear Sir or Madam ähnelt.
        /// </summary>
        public static string SalutationUnknown {
            get {
                return ResourceManager.GetString("SalutationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application as ähnelt.
        /// </summary>
        public static string Subjectprefix {
            get {
                return ResourceManager.GetString("Subjectprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Blog: ähnelt.
        /// </summary>
        public static string UsBlog {
            get {
                return ResourceManager.GetString("UsBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string UsBtnSave {
            get {
                return ResourceManager.GetString("UsBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Emailaddress: ähnelt.
        /// </summary>
        public static string UsEmailaddress {
            get {
                return ResourceManager.GetString("UsEmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email settings ähnelt.
        /// </summary>
        public static string UsEmailSettings {
            get {
                return ResourceManager.GetString("UsEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Familyname: ähnelt.
        /// </summary>
        public static string UsFamilyname {
            get {
                return ResourceManager.GetString("UsFamilyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Firstname: ähnelt.
        /// </summary>
        public static string UsFirstname {
            get {
                return ResourceManager.GetString("UsFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your User settings ähnelt.
        /// </summary>
        public static string UsHeader {
            get {
                return ResourceManager.GetString("UsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personal Settings ähnelt.
        /// </summary>
        public static string UsPersonalSettings {
            get {
                return ResourceManager.GetString("UsPersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Phonenumber: ähnelt.
        /// </summary>
        public static string UsPhonenumber {
            get {
                return ResourceManager.GetString("UsPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP-Password: ähnelt.
        /// </summary>
        public static string UsSmtpPassword {
            get {
                return ResourceManager.GetString("UsSmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP-Port: ähnelt.
        /// </summary>
        public static string UsSmtpPort {
            get {
                return ResourceManager.GetString("UsSmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP-Server: ähnelt.
        /// </summary>
        public static string UsSmtpServer {
            get {
                return ResourceManager.GetString("UsSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP-Username: ähnelt.
        /// </summary>
        public static string UsSmtpUser {
            get {
                return ResourceManager.GetString("UsSmtpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Address: ähnelt.
        /// </summary>
        public static string UsStreet {
            get {
                return ResourceManager.GetString("UsStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Settings ähnelt.
        /// </summary>
        public static string UsTitle {
            get {
                return ResourceManager.GetString("UsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your ZIP and City: ähnelt.
        /// </summary>
        public static string UsZipCity {
            get {
                return ResourceManager.GetString("UsZipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application details ähnelt.
        /// </summary>
        public static string WJAApplication {
            get {
                return ResourceManager.GetString("WJAApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        public static string WJABtnConfig {
            get {
                return ResourceManager.GetString("WJABtnConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database ähnelt.
        /// </summary>
        public static string WJABtnDatabase {
            get {
                return ResourceManager.GetString("WJABtnDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate ähnelt.
        /// </summary>
        public static string WJABtnGenerate {
            get {
                return ResourceManager.GetString("WJABtnGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City: ähnelt.
        /// </summary>
        public static string WJACity {
            get {
                return ResourceManager.GetString("WJACity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companydetails ähnelt.
        /// </summary>
        public static string WJACompanyDetails {
            get {
                return ResourceManager.GetString("WJACompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company Name: ähnelt.
        /// </summary>
        public static string WJACompanyName {
            get {
                return ResourceManager.GetString("WJACompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companies Street: ähnelt.
        /// </summary>
        public static string WJACompanyStreet {
            get {
                return ResourceManager.GetString("WJACompanyStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact person ähnelt.
        /// </summary>
        public static string WJAContact {
            get {
                return ResourceManager.GetString("WJAContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string WJAContactName {
            get {
                return ResourceManager.GetString("WJAContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emailaddress: ähnelt.
        /// </summary>
        public static string WJAEmail {
            get {
                return ResourceManager.GetString("WJAEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender: ähnelt.
        /// </summary>
        public static string WJAGender {
            get {
                return ResourceManager.GetString("WJAGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write your Job Applications ähnelt.
        /// </summary>
        public static string WJAHeader {
            get {
                return ResourceManager.GetString("WJAHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jobtitle: ähnelt.
        /// </summary>
        public static string WJAJobtitle {
            get {
                return ResourceManager.GetString("WJAJobtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL: ähnelt.
        /// </summary>
        public static string WJAUrl {
            get {
                return ResourceManager.GetString("WJAUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZIP Code: ähnelt.
        /// </summary>
        public static string WJAZip {
            get {
                return ResourceManager.GetString("WJAZip", resourceCulture);
            }
        }
    }
}
